site_name: "COVID-19 Intelligence Portal"
site_author: "Daksh Vanshaj"

nav:
  - Home: index.md
  - Business Context: business_context.md
  - Infrastructure & Setup: infrastructure.md
  - Intelligence & Automation:
      - AI Intelligence Setup: ai_intelligence_setup.md
      - n8n Workflow Logic: n8n_workflow.md
  - Analysis Tools:
      - Power BI Analysis: powerbi_analysis.md
      - Excel Risk Evaluation: excel_analysis.md
  - Production & Cloud: cloud_production.md

theme:
  name: material
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  primary: teal
  accent: amber
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    # - navigation.instant  ## turning it on causes mermaid diagrams to not load

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

repo_url: https://github.com/dakshvanshaj/-End-to-End-COVID-19-Data-Analysis-AI-Early-Warning-System
repo_name: "End-to-End-COVID-Pipeline"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dakshvanshaj

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daksh-vanshaj-9a9650344/
